global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 3m
  repeat_interval: 7m
  receiver: 'default'
  routes:
    - match:
        severity: 'load'
      receiver: 'webhook_up'

receivers:
  - name: 'default'
  - name: 'webhook_up'
    webhook_configs:
      - url: 'http://app:5000/slack' #Can be used telegram chat

