version: '3.8'

services:
  autoscaler:
    image: app_service_scaler
    ports:
      - "5033:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  networks:
      - app_network
