name: App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Build Docker Images
        run: |
          docker build -t app_service .
          docker build . -t app_service_scaler -f dockerscale/Dockerfile
          docker build . -t app_monitor -f dockermonitor/Dockerfile

  start_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Stop previous
        continue-on-error: true
        run: |
          docker service rm $(docker service ls -q)

      - name: Run tests
        run: | 
          docker stack deploy -c docker-compose.yml testdeploy
          docker stack deploy -c ./test/docker-compose.yml testdeploy
          sleep 200
          docker service logs testdeploy_tester
          docker service rm $(docker service ls -q)

  deploy:
    runs-on: ubuntu-latest
    needs: start_tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Docker Swarm
        run: |
          docker stack deploy -c docker-compose.yml testdeploy

